name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache CRC binary
        id: cache-crc-binary
        uses: actions/cache@v2
        with:
          path: crc
          key: ${{ runner.os }}-crc

      # curl -LO https://dl.fedoraproject.org/pub/alt/okd-crc/linux-amd64/crc
      - name: Download CRC binary
        if: steps.cache-crc-binary.outputs.cache-hit != 'true'
        run: |
          touch crc
          chmod +x crc
          echo hello

      - name: Setup and start CRC
        run: |
          sudo apt-get update -y
          sudo apt-get install -y qemu-kvm libvirt-daemon libvirt-daemon-system network-manager
          sudo cp crc /usr/local/bin/crc
          crc version
          crc setup
          crc start
